spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5434/quote_db
    username: dev-user
    password: mysecretpassword
    driverClassName: org.postgresql.Driver
